name: Deploy Nuxt 3 App

on:
    workflow_dispatch:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        
    - name: Install node_modules
      run: npm i

    - name: Install dependencies
      run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

    - name: Build Nuxt 3 app
      run: npm run build

    - name: Generate static files
      run: npx nuxi generate

    - name: Deploy to FTP 
      uses: SamKirkland/FTP-Deploy-Action@4.3.3 
      with: 
        server: 3117460654.cloudylink.com
        username: arashmz@foodayapp.freehost.io 
        password: tsvmbn1ynh
        local-dir: ./dist/
        server-dir: ./public_html/