name: Deploy Nuxt 3 App 
 
on: 
  workflow_dispatch: 
  push: 
    branches: 
      - main 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout 
      uses: actions/checkout@v3 
 
    - name: Setup Node.js 
      uses: actions/setup-node@v3 
      with: 
        node-version: 16 
 
    - name: Install dependencies 
      run: npm ci 
 
    - name: Build Nuxt 3 app 
      run: npm run build 
 
    - name: Generate static files 
      run: npm run generate 
 
    - name: Deploy to FTP 
      uses: crimx/browsersync-action@v1 
      with: 
        cli: | 
          npx browsersync@2.27.5 -f 'dist/**/*' --host='ftp.enterflash.com' --server='dist' --codeSync=false --port=8080 --directory=true 
          sleep 600 # Wait for some time to keep job alive 
        browsersync-url: >- 
            3117460654.cloudylink.com 
        browsersync-username:   arashmz@foodayapp.freehost.io
        browsersync-password: 
        browsersync-directory: /public_html 